-- 코드를 입력하세요
SELECT f.FLAVOR
FROM FIRST_HALF AS f
LEFT JOIN (
  SELECT FLAVOR, SUM(TOTAL_ORDER) AS july_sum
  FROM JULY
  GROUP BY FLAVOR
) AS j
  ON j.FLAVOR = f.FLAVOR
ORDER BY (f.TOTAL_ORDER + IFNULL(j.july_sum, 0)) DESC,
         f.FLAVOR ASC   
LIMIT 3;
