-- 코드를 작성해주세요
SELECT
    COUNT(*) AS FISH_COUNT,
    MONTH(STR_TO_DATE(LEFT(REPLACE(CAST(`TIME` AS CHAR), '/', '-'), 10), '%Y-%m-%d')) AS MONTH
FROM FISH_INFO
GROUP BY MONTH(STR_TO_DATE(LEFT(REPLACE(CAST(`TIME` AS CHAR), '/', '-'), 10), '%Y-%m-%d'))
ORDER BY MONTH;